// js/core/state.js

// 1. Глобальные переменные нашего приложения
export const state = {
    currentLang: "RUS",
    percent: 0,
    gTarget: 8000,
    cSav: 0
};

// 2. Объект с переводами
export const TRANSLATIONS = {
    RUS: {
    t_work_data: "Данные о работе", l_date: "📅 Дата", l_status: "📌 Статус",
    opt_work: "💼 Работа", opt_l4: "💊 Больничный (L4)", opt_urlop: "🌴 Отпуск",
    l_end_date: "🏁 По (включительно)", l_object: "📍 Объект / Город", 
    l_abroad: "🌍 Заграница (EUR)", l_diet: "🥪 Командировка (Диета)",
    t_logistics: "Логистика и Часы", l_car: "🚛 Авто", l_route: "🛣 Маршрут",
    l_hours: "⏱ На объекте (ч)", l_drive: "🚗 За рулем (ч)", btn_send_shift: "Отправить отчет",
    t_progress: "🎯 Моя копилка", t_audit: "📊 Интерактивный аудит ЗП",
    l_month_audit: "📅 Месяц", l_card: "💰 Пришло на карту", btn_audit: "Посчитать конверт",
    t_history: "📜 История и редактирование", l_month_history: "Выбери месяц", btn_history: "Показать смены",
    t_export: "📥 Экспорт Excel", l_month_export: "Выбери месяц", btn_export: "Прислать Excel в чат",
    t_lang: "Язык интерфейса", l_lang_select: "🌐 Язык", t_goal: "🎯 Моя финансовая цель", l_goal_name: "Название",
    l_goal_sum: "Сумма (zł)", t_profile: "Финансовый профиль (Ставки)", btn_save_settings: "Сохранить изменения",
    alert_hours: "⚠️ Укажи часы работы ИЛИ за рулем!", alert_audit: "⚠️ Выбери месяц и введи сумму!", alert_history: "⚠️ Выбери месяц для просмотра истории!",
    mot_start: "Начало положено! 🚀 Отложи первую сумму.", mot_good: "Отличный старт! Двигаемся дальше. 💼", mot_fast: "Хороший темп! Копилка пополняется. 🔥", mot_close: "Уже близко! Поднажми! 💪", mot_done: "ЦЕЛЬ ДОСТИГНУТА! 🎉 Ты супер-профи!",
    default_goal: "Моя цель", objectInput: "Любой текст", routeInput: "Откуда - Куда", cardAmount: "Сумма в zł", goalNameInput: "Дом у моря", goalMotivation: "Загружаем данные...",
    t_analytics: "📈 Топ объектов", l_month_analytics: "Выбери месяц", btn_analytics: "Показать Топ объектов",
    l_goal_date: "К какому сроку?", l_base_rate: "💳 Офиц. ставка (zł/h)", l_env: "✉️ Конверт (zł/h)", l_rate_eur: "💶 Ставка (EUR/h)", l_drive_zl: "🚗 Руль (zł/h)", l_drive_eur: "🚙 Руль (EUR/h)",
    t_garage: "Мой Гараж", 
    t_garage_desc: "Кася может автоматически распознать марку и номер машины по фотографии!",
    t_nav: "Навигация", 
    t_nav_desc: "Введи точки маршрута, и Кася проложит путь прямо в твоем навигаторе!",
    t_envelope_desc: "Кася сверит твои часы с переводами на карту и скажет, сколько злотых шеф должен отдать в конверте!",
    t_history_desc: "Кася поднимет архивы за выбранный месяц, чтобы ты мог просмотреть или изменить свои записи.",
    t_export_desc: "Кася аккуратно соберет все твои смены за месяц и пришлет готовый файл Excel прямо в Телеграм!",
    t_analytics_desc: "Кася проанализирует твои смены и покажет, какие объекты принесли тебе больше всего часов в этом месяце."
  },
    UKR: {
    t_work_data: "Дані про роботу", l_date: "📅 Дата", l_status: "📌 Статус",
    opt_work: "💼 Робота", opt_l4: "💊 Лікарняний (L4)", opt_urlop: "🌴 Відпустка",
    l_end_date: "🏁 По (включно)", l_object: "📍 Об'єкт / Місто", 
    l_abroad: "🌍 Закордон (EUR)", l_diet: "🥪 Відрядження (Дієта)",
    t_logistics: "Логістика та Години", l_car: "🚛 Авто", l_route: "🛣 Маршрут",
    l_hours: "⏱ На об'єкті (год)", l_drive: "🚗 За кермом (год)", btn_send_shift: "Відправити звіт",
    t_progress: "🎯 Моя скарбничка", t_audit: "📊 Інтерактивний аудит ЗП",
    l_month_audit: "📅 Місяць", l_card: "💰 Прийшло на карту", btn_audit: "Порахувати конверт",
    t_history: "📜 Історія", l_month_history: "Обери місяць", btn_history: "Показати зміни",
    t_export: "📥 Експорт Excel", l_month_export: "Обери місяць", btn_export: "Надіслати Excel у чат",
    t_lang: "Мова інтерфейсу", l_lang_select: "🌐 Мова", t_goal: "🎯 Моя фінансова ціль", l_goal_name: "Назва",
    l_goal_sum: "Сума (zł)", t_profile: "Фінансовий профіль (Ставки)", btn_save_settings: "Зберегти зміни",
    alert_hours: "⚠️ Вкажи години роботи АБО за кермом!", alert_audit: "⚠️ Обери місяць та введи суму!", alert_history: "⚠️ Обери місяць для перегляду історії!",
    mot_start: "Початок покладено! 🚀", mot_good: "Гарний старт! 💼", mot_fast: "Хороший темп! 🔥", mot_close: "Вже близько! 💪", mot_done: "ЦІЛЬ ДОСЯГНУТА! 🎉",
    default_goal: "Моя ціль", objectInput: "Будь-який текст", routeInput: "Звідки - Куди", cardAmount: "Сума в zł", goalNameInput: "Будинок біля моря", goalMotivation: "Завантажуємо дані...",
    t_analytics: "📈 Топ об'єктів", l_month_analytics: "Обери місяць", btn_analytics: "Показати Топ об'єктів",
    l_goal_date: "До якого терміну?", l_base_rate: "💳 Офіц. ставка (zł/h)", l_env: "✉️ Конверт (zł/h)", l_rate_eur: "💶 Ставка (EUR/h)", l_drive_zl: "🚗 Кермо (zł/h)", l_drive_eur: "🚙 Кермо (EUR/h)",
    t_garage: "Мій Гараж", 
    t_garage_desc: "Кася може автоматично розпізнати марку та номер машини за фотографією!",
    t_nav: "Навігація", 
    t_nav_desc: "Введи точки маршруту, і Кася проложить шлях прямо в твоєму навігаторі!",
    t_envelope_desc: "Кася звірить твої години з переказами на карту і скаже, скільки злотих шеф має віддати у конверті!",
    t_history_desc: "Кася підніме архіви за обраний місяць, щоб ти міг переглянути або змінити свої записи.",
    t_export_desc: "Кася акуратно збере всі твої зміни за місяць і надішле готовий файл Excel прямо в Телеграм!",
    t_analytics_desc: "Кася проаналізує твої зміни і покаже, які об'єкти принесли тобі найбільше годин цього місяця."
    },
    PL: {
    t_work_data: "Dane o pracy", l_date: "📅 Data", l_status: "📌 Status",
    opt_work: "💼 Praca", opt_l4: "💊 Zwolnienie (L4)", opt_urlop: "🌴 Urlop",
    l_end_date: "🏁 Do (włącznie)", l_object: "📍 Obiekt / Miasto", 
    l_abroad: "🌍 Zagranica (EUR)", l_diet: "🥪 Delegacja (Dieta)",
    t_logistics: "Logistyka i Godziny", l_car: "🚛 Auto", l_route: "🛣 Trasa",
    l_hours: "⏱ Na obiekcie (h)", l_drive: "🚗 Za kierownicą (h)", btn_send_shift: "Wyślij raport",
    t_progress: "🎯 Moja skarbonka", t_audit: "📊 Interaktywny audyt",
    l_month_audit: "📅 Miesiąc", l_card: "💰 Wpłynęło na konto", btn_audit: "Oblicz kopertę",
    t_history: "📜 Historia", l_month_history: "Wybierz miesiąc", btn_history: "Pokaż zmiany",
    t_export: "📥 Eksport Excel", l_month_export: "Wybierz miesiąc", btn_export: "Wyślij Excel",
    t_lang: "Język interfejsu", l_lang_select: "🌐 Język", t_goal: "🎯 Mój cel finansowy", l_goal_name: "Nazwa",
    l_goal_sum: "Kwota (zł)", t_profile: "Profil finansowy (Stawki)", btn_save_settings: "Zapisz zmiany",
    alert_hours: "⚠️ Podaj godziny pracy LUB za kierownicą!", alert_audit: "⚠️ Wybierz miesiąc i wpisz kwotę!", alert_history: "⚠️ Wybierz miesiąc!",
    mot_start: "Początek zrobiony! 🚀", mot_good: "Świetny start! 💼", mot_fast: "Dobre tempo! 🔥", mot_close: "Już blisko! 💪", mot_done: "CEL OSIĄGNIĘTY! 🎉",
    default_goal: "Mój cel", objectInput: "Dowolny tekst", routeInput: "Skąd - Dokąd", cardAmount: "Kwota w zł", goalNameInput: "Dom nad morzem", goalMotivation: "Wczytywanie...",
    t_analytics: "📈 Top obiektów", l_month_analytics: "Wybierz miesiąc", btn_analytics: "Pokaż Top obiektów",
    l_goal_date: "Do kiedy?", l_base_rate: "💳 Ofic. stawka (zł/h)", l_env: "✉️ Koperta (zł/h)", l_rate_eur: "💶 Stawka (EUR/h)", l_drive_zl: "🚗 Kółko (zł/h)", l_drive_eur: "🚙 Kółko (EUR/h)",
    t_garage: "Mój Garaż", 
    t_garage_desc: "Kasia może automatycznie rozpoznać markę i numer rejestracyjny samochodu na podstawie zdjęcia!",
    t_nav: "Nawigacja", 
    t_nav_desc: "Wpisz punkty trasy, a Kasia wyznaczy drogę prosto w Twojej nawigacji!",
    t_envelope_desc: "Kasia porówna Twoje godziny z przelewami na konto i powie, ile złotych szef powinien oddać w kopercie!",
    t_history_desc: "Kasia wyciągnie archiwa za wybrany miesiąc, abyś mógł przejrzeć lub edytować swoje wpisy.",
    t_export_desc: "Kasia starannie zbierze wszystkie Twoje zmiany za miesiąc i wyśle gotowy plik Excel prosto na Telegram!",
    t_analytics_desc: "Kasia przeanalizuje Twoje zmiany i pokaże, które obiekty przyniosły Ci najwięcej godzin w tym miesiącu."
    }
};